### ISSUE TITLE
Update to base SDK to iOS 9.0

### ISSUE THREAD

**Issue by RubenSandwich** [cmoa/cmoa-app-ios#7]
In order to submit a update to the iOS app store, we need to build with the newest SDK which for iOS is 9.0. This is going to open up a whole can of deprecations that I will manage here:
- [X] Use UIAlertController for iOS 8+ alert views and action sheets: #8
- [X] Update Google Analytics package: #9 
- [X] Update all traffic to HTTPS or whitelist: #12
- [X] Fix compiler warnings: #15 
- [X] Fix opened and closed accessory view on hours view: #14
